# Generated by Django 5.2.5 on 2026-04-30 12:22

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_unify_user_names_and_brazilian_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagem JPG, PNG ou WEBP de até 2 MB.', null=True, upload_to=profiles.models.avatar_upload_path, verbose_name='Foto de perfil'),
        ),
    ]
