# Generated by Django 5.2.5 on 2026-05-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_add_avatar_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_confirm_default',
            field=models.BooleanField(default=False, help_text='Novas transações pendentes terão efetivação automática por padrão', verbose_name='Efetivar transações automaticamente'),
        ),
    ]
