# Generated by Django 5.2.5 on 2026-04-28 02:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Alvo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Soma dos aportes; atualizado automaticamente.', max_digits=12, verbose_name='Valor Atual')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('icon', models.CharField(choices=[('🎯', 'Alvo'), ('💰', 'Dinheiro'), ('🏠', 'Casa'), ('🚗', 'Carro'), ('✈️', 'Viagem'), ('🎓', 'Educação'), ('💍', 'Casamento'), ('👶', 'Bebê'), ('🏥', 'Saúde'), ('💻', 'Tecnologia'), ('🛡️', 'Reserva de Emergência'), ('🎁', 'Presente')], default='🎯', max_length=10, verbose_name='Ícone')),
                ('color', models.CharField(choices=[('#3B82F6', 'Azul'), ('#10B981', 'Verde'), ('#8B5CF6', 'Roxo'), ('#F59E0B', 'Amarelo'), ('#EF4444', 'Vermelho'), ('#06B6D4', 'Ciano'), ('#EC4899', 'Rosa'), ('#F97316', 'Laranja')], default='#3B82F6', max_length=7, verbose_name='Cor')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data do Aporte')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goals.goal', verbose_name='Meta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_contributions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Aporte',
                'verbose_name_plural': 'Aportes',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='goals_goal_user_id_7ad9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'deadline'], name='goals_goal_user_id_38b5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='goalcontribution',
            index=models.Index(fields=['goal', 'date'], name='goals_goalc_goal_id_042e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='goalcontribution',
            index=models.Index(fields=['user', 'date'], name='goals_goalc_user_id_54e9da_idx'),
        ),
    ]
