# Generated by Django 5.2.5 on 2026-05-20 16:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_alter_account_account_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição')),
                ('transfer_date', models.DateField(verbose_name='Data da transferência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='accounts.account', verbose_name='Conta de origem')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='accounts.account', verbose_name='Conta de destino')),
                ('user', models.ForeignKey(help_text='Owner of this transfer', on_delete=django.db.models.deletion.CASCADE, related_name='fund_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferência entre contas',
                'verbose_name_plural': 'Transferências entre contas',
                'ordering': ['-transfer_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'transfer_date'], name='accounts_fu_user_id_02c174_idx'), models.Index(fields=['user', 'from_account'], name='accounts_fu_user_id_19cee7_idx'), models.Index(fields=['user', 'to_account'], name='accounts_fu_user_id_bc0a5a_idx')],
            },
        ),
    ]
