# Generated by Django 5.2.5 on 2026-09-18 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fund_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjustment_date', models.DateField()),
                ('reason', models.CharField(max_length=300)),
                ('client_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_adjustments', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_balance_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-adjustment_date', '-created_at'],
                'indexes': [models.Index(fields=['account', 'adjustment_date'], name='accounts_ac_account_3336e7_idx'), models.Index(fields=['user', 'adjustment_date'], name='accounts_ac_user_id_b95264_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'client_id'), name='unique_account_adjustment_client_id_per_user')],
            },
        ),
    ]
