# Generated by Django 5.2.5 on 2026-09-18 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountbalanceadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransfer',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Identificador idempotente'),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='destination_context',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Contexto de destino'),
        ),
        migrations.AddConstraint(
            model_name='fundtransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id', ''), _negated=True), fields=('user', 'client_id'), name='unique_transfer_client_id_per_user'),
        ),
    ]
