# Generated by Django 5.2.5 on 2026-05-16 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_alter_account_account_type_and_more'),
        ('categories', '0002_alter_category_options_alter_category_category_type_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='auto_confirm',
            field=models.BooleanField(default=False, help_text='Se True, efetiva automaticamente na data via cron', verbose_name='Efetivar automaticamente'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp de quando a transação foi efetivada', null=True, verbose_name='Efetivada em'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Efetivada'), ('CANCELLED', 'Cancelada')], default='PENDING', help_text='Status da transação: pendente, efetivada ou cancelada', max_length=10, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='transaction_user_id_9cef77_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'transaction_date', 'auto_confirm'], name='transaction_status_4375a7_idx'),
        ),
    ]
