# Generated by Django 5.2.5 on 2026-05-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('transactions', '0003_set_existing_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='tags.tag', verbose_name='Tags'),
        ),
    ]
