# Generated by Django 5.2.5 on 2026-04-29 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveSmallIntegerField(help_text='Percentage threshold that was crossed (e.g. 70, 90, 100).')),
                ('spent_at_trigger', models.DecimalField(decimal_places=2, help_text='Snapshot of the spent_amount when the alert fired.', max_digits=12)),
                ('percentage_at_trigger', models.DecimalField(decimal_places=2, help_text='Snapshot of the percentage used when the alert fired.', max_digits=6)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgets.budget')),
                ('user', models.ForeignKey(help_text='Denormalized for fast per-user queries without joining Budget.', on_delete=django.db.models.deletion.CASCADE, related_name='budget_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Orçamento',
                'verbose_name_plural': 'Alertas de Orçamento',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['user', 'acknowledged_at'], name='budgets_bud_user_id_cbb81d_idx'), models.Index(fields=['budget', 'triggered_at'], name='budgets_bud_budget__ce4b55_idx')],
                'constraints': [models.UniqueConstraint(fields=('budget', 'threshold'), name='unique_alert_per_budget_threshold')],
            },
        ),
    ]
