# Generated by Django 5.2.5 on 2026-05-05 02:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budgetalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('renda_prevista', models.DecimalField(decimal_places=2, help_text='Total de receitas esperadas no mês.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Renda Prevista')),
                ('teto_despesas', models.DecimalField(decimal_places=2, help_text='Limite máximo de gastos permitidos no mês.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Teto de Despesas')),
                ('reserva_dividas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor separado para pagamento de dívidas (preparado para FIN-7).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Reserva Dívidas')),
                ('reserva_metas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor separado para aportes em metas (preparado para FIN-9).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Reserva Metas')),
                ('reserva_investimentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor separado para investimentos (preparado para FIN-10).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Reserva Investimentos')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano Mensal',
                'verbose_name_plural': 'Planos Mensais',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='budgets_mon_user_id_f23df7_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_monthly_plan_per_user'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='monthly_plan_valid_month'), models.CheckConstraint(condition=models.Q(('year__gte', 2000), ('year__lte', 2100)), name='monthly_plan_valid_year')],
            },
        ),
    ]
