# Generated by Django 5.2.5 on 2026-05-09 00:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_monthly_plan'),
        ('categories', '0002_alter_category_options_alter_category_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='savings_goal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor que o usuário deseja economizar no mês.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Meta de Economia'),
        ),
        migrations.AlterField(
            model_name='budgetalert',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgets.budget'),
        ),
        migrations.CreateModel(
            name='MonthlyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Planejado')),
                ('alert_threshold', models.PositiveSmallIntegerField(blank=True, help_text='Percentual de uso para disparar alerta (ex: 80 = alertar ao atingir 80%).', null=True, verbose_name='Alerta (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='categories.category', verbose_name='Categoria')),
                ('monthly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.monthlyplan', verbose_name='Plano Mensal')),
            ],
            options={
                'verbose_name': 'Item do Plano',
                'verbose_name_plural': 'Itens do Plano',
                'ordering': ['category__name'],
            },
        ),
        migrations.AddField(
            model_name='budgetalert',
            name='plan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgets.monthlyplanitem', verbose_name='Item do Plano'),
        ),
        migrations.AddIndex(
            model_name='monthlyplanitem',
            index=models.Index(fields=['monthly_plan', 'category'], name='budgets_mon_monthly_e16e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyplanitem',
            index=models.Index(fields=['monthly_plan'], name='budgets_mon_monthly_ed414e_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyplanitem',
            constraint=models.UniqueConstraint(fields=('monthly_plan', 'category'), name='unique_plan_item_per_category'),
        ),
    ]
