# Generated by Django 5.2.5 on 2026-05-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_sprint7_monthly_plan_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('ACTIVE', 'Ativo'), ('CLOSED', 'Encerrado')], default='DRAFT', max_length=10, verbose_name='Status'),
        ),
    ]
