# Generated by Django 5.2.5 on 2026-09-18 19:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_accountbalanceadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty', models.CharField(max_length=150)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('SETTLED', 'Liquidado'), ('WRITTEN_OFF', 'Baixado como perda')], default='ACTIVE', max_length=16)),
                ('client_id', models.CharField(max_length=64)),
                ('written_off_at', models.DateTimeField(blank=True, null=True)),
                ('write_off_reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans_originated', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_receivable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-loan_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('settlement_date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('client_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='receivables.loanreceivable')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_settlements_received', to='accounts.account')),
            ],
            options={
                'ordering': ['-settlement_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loanreceivable',
            index=models.Index(fields=['user', 'status'], name='receivables_user_id_a0a1eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanreceivable',
            constraint=models.UniqueConstraint(fields=('user', 'client_id'), name='unique_loan_client_id_per_user'),
        ),
        migrations.AddConstraint(
            model_name='loansettlement',
            constraint=models.UniqueConstraint(fields=('loan', 'client_id'), name='unique_settlement_client_id_per_loan'),
        ),
    ]
